# Copyright (c) 2018
# Cavium
#
# SPDX-License-Identifier: Apache-2.0
#
# Author: Federico Claramonte <fclaramonte@cavium.com>
# Author: chencho <smunoz@cavium.com>

version: '3'
volumes:
  config:
  data:
  test:

services:
  demo:
    image: chenchix/edgex-demo
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"
    container_name: edgex-demo
    hostname: edgex-demo
    networks:
      - edgex-network
    volumes:
      - config:/config
      - data:/data
      - test:/test
    environment:      
      - MQTT_HOST=127.0.0.1
      - EDGEX_HOST=127.0.0.1
      - ROOMS=room11 room21 room31

networks:                      
  edgex-network:            
    driver: "bridge"